definitions:
  models.User:
    properties:
      account_ids:
        items:
          type: integer
        type: array
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  services.getAccountResponse:
    properties:
      balance:
        type: number
      id:
        type: integer
      name:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get account information
      parameters:
      - description: account_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.getAccountResponse'
      summary: get account information
      tags:
      - Accounts
  /users/{id}:
    get:
      consumes:
      - application/json
      description: get user information
      parameters:
      - description: user_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: get user information
      tags:
      - Users
  /users/{id}/accounts:
    get:
      consumes:
      - application/json
      description: list account information
      parameters:
      - description: user_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.getAccountResponse'
            type: array
      summary: list user account information
      tags:
      - Users
swagger: "2.0"
